# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fastgeojson_wrappers", use_symbols = TRUE, package_name = "fastgeojson")

#' @usage NULL
#' @useDynLib fastgeojson, .registration = TRUE
NULL

sf_geojson_str_impl <- function(x, auto_unbox, na, null) .Call(wrap__sf_geojson_str_impl, x, auto_unbox, na, null)

df_json_str_impl <- function(x, auto_unbox, dataframe, na, null) .Call(wrap__df_json_str_impl, x, auto_unbox, dataframe, na, null)

obj_json_str_impl <- function(x, auto_unbox, na, null) .Call(wrap__obj_json_str_impl, x, auto_unbox, na, null)


# nolint end
